### ISSUE TITLE
Working towards a polished reference style

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#10]
@banesullivan Thanks for all of the improvements!  I've added a new cell to the notebook, `kale.ipynb`.  It's cell #11 (I think).  The purpose of this cell is to try to establish a single figure that represents the canonical style that we want the others to follow.  It's getting there.  I've added a bunch of TODOs to the cell that I'd like you to address.  I opted for TODOs in the cell because I'm not certain how to connect issues with specific lines of code in a Jupyter notebook.  Happy to chat about this.  The complete contents of the cell are pasted below for reference.

```python
# TODO: Bane, this is the cell where I'm working towards a standard reference format
# TODO: Please see the TODOs in here
# Also note that when the igure first renders it applears sort of big and slightly blurry.
# After I click on it it looks nice and sharp with reasonably sized fonts.  Can we make that
# happen in a way that doesn't require a click?

import numpy as np

# TODO: How do I maniputlate the quantity geometic moment here?
# There's a lot of experimenting to do in order to see the best way to plot things.
# For example I might like to take the cube root of this or the log or sigmoid.
engine.mesh.active_scalars_name = "geometric_moment"

# TODO: The same fontsizes seem to produce different sized fonts on the figure
# I'd like all fonts to be the same size and type
COLORBAR_FONT_SIZE = 30
AXES_FONT_SIZE = 30
TIMESTEP_FONT_SIZE = 30 


SCALAR_BAR_OPTS = dict(
    # Position (coordinates are on the viewport)
    vertical=True,
    height=0.20,
    width=0.05,
    position_x=0.05,
    position_y=0.40,
    # Labels
    title_font_size=AXES_FONT_SIZE,
    label_font_size=AXES_FONT_SIZE,
    n_labels=3,
    italic=False,
    fmt="%.1f",
    font_family="arial",
    shadow=True,
)

# TODO: How do I specifiy specific contour levels?
# TODO: N_CONTOURS seems to work but I'd like to specify specific values
CONTOUR_LEVELS = np.linspace(-10e9, 10e9, 11)
N_CONTOURS = len(CONTOUR_LEVELS)

contour, edges = contour_banded(
    engine.algorithm,
    N_CONTOURS, 
    rng=engine.clim(),
    scalars=engine.mesh.active_scalars_name,
)

pl = pv.Plotter()
pl.add_mesh(engine.boundary, color="k", line_width=LINE_WIDTH)
pl.add_mesh(
    contour,
    cmap=COLOR_MAPS[engine.mesh.active_scalars_name],
    # clim=engine.clim(),
    clim=[np.min(CONTOUR_LEVELS), np.max(CONTOUR_LEVELS)], # TODO: Trying to set colorbar to by summetric here and limited.
    scalars=engine.mesh.active_scalars_name,
    n_colors=N_CONTOURS - 1,
    scalar_bar_args=SCALAR_BAR_OPTS,
    label="asdf" # TODO: How do I set title of colorbar?
)
pl.add_mesh(edges.GetOutputPort(1), color=CONTOUR_LINE_COLOR, line_width=LINE_WIDTH) # TODO: How do I make contours here match banded contours?
pl.add_text(f"time step: {1:05d}", name="time-step-label", font_size=TIMESTEP_FONT_SIZE)
pl.show_grid(xlabel="longitude", ylabel="latitude", zlabel="depth", font_size=AXES_FONT_SIZE, bold=False)
pl.camera_position = cpos
show_ui(engine, pl)
```

**Comment by banesullivan** [comment]
> Also note that when the igure first renders it applears sort of big and slightly blurry.
> After I click on it it looks nice and sharp with reasonably sized fonts.  Can we make that
> happen in a way that doesn't require a click?

This is an upstream issue which should get fixed soon. See https://github.com/Kitware/trame-vtk/issues/25

**Comment by banesullivan** [comment]
> TODO: How do I maniputlate the quantity geometic moment here?
> There's a lot of experimenting to do in order to see the best way to plot things.
> For example I might like to take the cube root of this or the log or sigmoid.

Hm. There are a number of ways to do this but it gets a little tricky since we are dealing with a time series. Let me think about this to come up with a simplish/streamlined way to do this

**Comment by banesullivan** [comment]
> TODO: The same fontsizes seem to produce different sized fonts on the figure
> I'd like all fonts to be the same size and type

Yeah... there are a lot of font sizing issues in VTK and PyVista. This will requiring some manual toying with to get right

**Comment by banesullivan** [comment]
> TODO: How do I specifiy specific contour levels?
> TODO: N_CONTOURS seems to work but I'd like to specify specific values

I'll make sure this works and provide an example in the code

**Comment by banesullivan** [comment]
> TODO: How do I set title of colorbar?

Set the `'title'` in the `SCALAR_BAR_OPTS` dictionary

**Comment by banesullivan** [comment]
> TODO: How do I make contours here match banded contours?

Not sure I follow...

**Comment by brendanjmeade** [comment]
@banesullivan Following up on just two issues here:
1. How do I set the specific contour levels?
2. CLIM is working great now!  However, when the cell values exceed the max value in CLIM they banded contour color for them becomes transparent clear (see attached example).  Is there a way to make the color simply be constant for the max of CLIM and above.  Same for the minimum and below too.  In the matplotlib world, this is accomplished with the extend keyword.
<img width="997" alt="Screenshot 2023-02-15 at 5 43 48 PM" src="https://user-images.githubusercontent.com/4225359/219206873-6d361ca3-3831-4911-acf8-176969ed019c.png">

**Comment by banesullivan** [comment]
> ...is there a way to make the color simply be constant for the max of CLIM and above ...

This is done with `clipping=False` for the `contour_banded` filter. I went ahead and made `False` the default in 35520761cdc85d4a83534d0acfd4de58ff53543f

**Comment by banesullivan** [comment]
Further, I'd recommend use an above/below color to indicate these are outside of the range with `below_color='blue'` or  `above_color='red'`. Ref https://docs.pyvista.org/examples/02-plot/scalar-bars.html#sphx-glr-examples-02-plot-scalar-bars-py

**Comment by banesullivan** [comment]
> How do I set the specific contour levels?

This is working, we just need to pass the contour levels to the contouring function. I've made this more clear and updated usage in de77254d5a859faebeb29eb1f3a707d46f2d8d50

**Comment by banesullivan** [comment]
I think we've addressed everything except manipulating the quantities here. I will add that next

**Comment by banesullivan** [comment]
I added an example of how to manipulate an array in 7fa79d92736b6ac994f480aeed5dadf4c200c7af

There is also a new notebook showing this off more minimally in `manipulate-algorithm.ipynb`

I added an example with cuberoot in`kale.ipynb`

**Comment by brendanjmeade** [comment]
> This is done with clipping=False for the contour_banded filter. I went ahead and made False the default in https://github.com/brendanjmeade/kale/commit/35520761cdc85d4a83534d0acfd4de58ff53543f

Thanks for solving this!

**Comment by brendanjmeade** [comment]
> This is working, we just need to pass the contour levels to the contouring function. I've made this more clear and updated usage in [de77254](https://github.com/brendanjmeade/kale/commit/de77254d5a859faebeb29eb1f3a707d46f2d8d50)

This works fantastically.  Thanks!

**Comment by brendanjmeade** [comment]
> I added an example of how to manipulate an array in [7fa79d9](https://github.com/brendanjmeade/kale/commit/7fa79d92736b6ac994f480aeed5dadf4c200c7af)
> 
> There is also a new notebook showing this off more minimally in `manipulate-algorithm.ipynb`
> 
> I added an example with cuberoot in`kale.ipynb`

This is as esoteric as promised but totally workable.  The cube root is a favorit of mine.  Very cool and useful!
