### ISSUE TITLE
Writing .vtk files from .msh files

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#11]
@banesullivan This one is a little strange.  I have two .msh files (both attached) one low and one high resolution triangulations of the same surface.  Both run through all of my calculations just fine.  However, the code I have only writes the low resolution one properly to a .vtk file while the higher resolution one doesn't write using the approach that I take (https://github.com/brendanjmeade/skies/blob/12ca45c25b9894b0ebeb702f796741d51c8603d8/skies/skies.py#L1547).  I was hoping you could show me how you write .vtk files from .msh files so that I can do this properly for in general.  Happy to provide more information.

[cascadia_meshes.zip](https://github.com/brendanjmeade/kale/files/10714414/cascadia_meshes.zip)

**Comment by banesullivan** [comment]
How were these meshes produced? Are they GMesh meshes?

When using PyVista, it may not be necessary to convert these files to VTK meshes. PyVista supports a lot of different file formats through various VTK readers but also leverages [meshio](https://github.com/nschloe/meshio) for file IO. If these are indeed GMesh files, then a standard `pyvista.read()` is all it takes to load these data:

```py
import pyvista as pv
mesh = pv.read('input.msh')
```

If wanting to export to VTK (or any other format for that matter), call `.save()` with the desired extension:

```py
mesh.save('output.vtk')
```

**Comment by banesullivan** [comment]
See the latest changes in `subdivide.ipynb` which walks through how to use PyVista’s subdivision filter and save out to a `.msh` file using `meshio`.

I also added a bit at the end that compares the different subdividing methods:

![screenshot (2)](https://user-images.githubusercontent.com/22067021/218583364-fb5e8fa0-a685-49a0-8410-fffaba908ac0.png)
![screenshot (1)](https://user-images.githubusercontent.com/22067021/218583375-a5dbc78d-890c-4bfb-8338-ab9736f65f52.png)

**Comment by brendanjmeade** [comment]
@banesullivan Thanks for this.  The subdivisions all look great.  However, the .msh files that get written out appear problematic.  Specifically, gmsh can't open them and meshio seems to have problems as well (screenshots of error message attached).  I've attached an example .msh file that is written by the subdivide notebook, and would appreciate it if you could take a look.  I'm hoping that there's just some different way to write the subdivided mesh to disk that'll make it work?

[cascadia_118k.msh.zip](https://github.com/brendanjmeade/kale/files/10747479/cascadia_118k.msh.zip)
<img width="703" alt="Screenshot 2023-02-15 at 4 14 36 PM" src="https://user-images.githubusercontent.com/4225359/219167165-063eed9c-57b6-4cb2-8d0d-5ca0b2a0907d.png">
<img width="1137" alt="Screenshot 2023-02-15 at 4 14 56 PM" src="https://user-images.githubusercontent.com/4225359/219167175-438452a1-b70f-4eea-ba0f-777642ea18e8.png">

**Comment by banesullivan** [comment]
So. I think we can do this with ParaView. I've added a ParaView state file and a pvpython script to do the subdivision with ParaView and for it to export a gmsh file. Let's meet and talk through this to see if it works.

**Comment by brendanjmeade** [comment]
This is a step in the right direction.  I also need to see if I can create a .vtk file from the higher resolution .msh file (i.e. discretized in gmsh).

**Comment by brendanjmeade** [comment]
@banesullivan I think I've figured out a way to use the `.msh` files I produce with gmsh and convert them successfully to `.vtk` that works well with `kale`.  A description of how to do this can be found at:

https://github.com/brendanjmeade/skies/wiki/Converting-.msh-files-to-.vtk-files
