### ISSUE TITLE
Text and bar I don't intend to have

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#14]
@banesullivan In the 3-panel figure made by the final cell of: kale_single_step_erosion_figures_nankai.ipynb there is some anomalous text at the bottom and a horizontal black bar at the top (see attached figure).  I don't intend for these to be there, and I'd like to remove them.  Some notes:

- This bar at the top appears when I scale the resolution up.  I do this to create super-high-resolution screenshots.  At even higher resolutions, an additional bar appears on the right-hand side of the figure.
- The text and line widths look comically large in the Jupyter notebook but render very nicely as a saved figure.
- I feel like I'm drawing something unintentionally here, and that's what's showing up!

![kale_single_time_step_cumulative_slip_nankai_years_large](https://user-images.githubusercontent.com/4225359/229541286-a6a21fbb-a148-45d0-b167-a59f94afe12c.png)

**Comment by banesullivan** [comment]
This is odd. I'll make sure I can reproduce and will look into this

**Comment by banesullivan** [comment]
@brendanjmeade, would you please share a PyVista report to help me track this down?

```py
import pyvista as pv
print(pv.Report())
```

**Comment by brendanjmeade** [comment]
@banesullivan Sure thing:

--------------------------------------------------------------------------------
  Date: Tue Apr 11 12:11:20 2023 EDT

                OS : Darwin
            CPU(s) : 10
           Machine : arm64
      Architecture : 64bit
               RAM : 64.0 GiB
       Environment : Jupyter
       File system : apfs
        GPU Vendor : Apple
      GPU Renderer : Apple M1 Max
       GPU Version : 4.1 Metal - 83.1

  Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40)
  [Clang 14.0.6 ]

           pyvista : 0.38.1
               vtk : 9.2.5
             numpy : 1.24.2
           imageio : 2.25.0
            scooby : 0.7.1
             pooch : v1.6.0
        matplotlib : 3.6.2
           IPython : 8.8.0
          colorcet : 3.0.1
        ipyvtklink : 0.2.3
              tqdm : 4.64.1
            meshio : 5.3.4
        jupyterlab : 3.5.3
             trame : 2.2.6
      trame_client : 2.5.1
      trame_server : 2.8.1
         trame_vtk : 2.0.17
--------------------------------------------------------------------------------

**Comment by banesullivan** [comment]
For the text in the scene, it looks like it was adding a scalar bar to those scenes. I've disabled this with `show_scalar_bar=False,` in the `add_mesh` arguments for those subplots. I will push updates soon.

As for the black bar at the top... I can't reproduce this at the moment. If it continues to occur after my latest updates, we'll need to chat to see what's going wrong.

**Comment by brendanjmeade** [comment]
Thanks for the update and sounds good.  Will this change still show the colorbar under the middle figure? The black bar is strange and only appears when I make the figures really large.

**Comment by banesullivan** [comment]
Yep, it will! I'm currently refactoring a lot of this code to clean it up and place what I can in the `kale` module itself. I may inadvertently change some of your configurations, but I'll have it more consistent across notebooks.

**Comment by banesullivan** [comment]
Finally managed to reproduce the black line. Tracking upstream in https://github.com/pyvista/pyvista/issues/4296

**Comment by banesullivan** [comment]
> The text and line widths look comically large in the Jupyter notebook but render very nicely as a saved figure.

That's because of the `image_scale`. The image is scaled when the screenshot/figure is saved and the text is sized appropriately for that scale. However in Jupyter, we do not scale up the view as the rendering would not be responsive at that scale and the fonts look massive.

**Comment by banesullivan** [comment]
> I feel like I'm drawing something unintentionally here, and that's what's showing up!

This was just the case for the text at the bottom. #16 cleans all of this up

**Comment by banesullivan** [comment]
For the bar, let's limit the image scale to 14 for now. 15 seems to introduce the issue.
