### ISSUE TITLE
Organizing notebooks

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#17]
I've created a mess of notebooks with little organization.  After talking with @banesullivan we've agreed that a few single-purpose notebooks will serve future us well.

- [x] Plot cumulative slip and cumulative moment as two separate figures for a single time step. Proposed name: `cumulative_slip_geometric_moment_single_time.ipynb`
- [x] Plot cumulative slip at three different time steps in a single figure. Proposed name: `cumulative_slip_three_panel.ipynb`
- [x] Generate two separate animations of cumulative slip and geometric moment.  Proposed name: `cumulative_slip_geometric_moment_animations.ipynb`

**Comment by banesullivan** [comment]
Considering most of these notebooks are able to handle multiple variables (one at a time) I chose the following names respectively: `single_time.ipynb`, `three_times_panel.ipynb`, and `animations.ipynb`. These three notebooks will be placed under a `simple/` directory in my upcoming PR

**Comment by banesullivan** [comment]
Handled in 67fab6a42211638b1c4af0e6678d7d8d3c4fc6da -- note that these notebooks need to be adjusted for the data they are plotting and currently produce "meh" results
