### ISSUE TITLE
Bane's combined information idea

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#18]
@banesullivan's cool idea to show both geometric moment and cumulative slip on the same plot animation.  At each cell centroid draw a sphere.  The size of the sphere is proportional to geometric moment.  The color of the sphere color mapped to geometric slip.  Start with a single time step figure to get iterate on the style.

**Comment by banesullivan** [comment]
I was hoping we could leverage some recent work in PyVista (see https://github.com/pyvista/pyvista/pull/4366), but it doesn't support algorithms/pipelines 😞 

So. We'll have to adopt PyVista's `glyph()` filter: https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.DataSetFilters.glyph.html#glyph

This filter's source code is a beast and the source code can be a bit delicate. Further, we have to be careful how big the glyhping geometry we give it -- it should be a very low-resolution sphere.

I will provide a copy/pasted version of this filter in the `kale` module that will provide algorithm support that we'll maintain until PyVista solves filter pipelines (ref https://github.com/pyvista/pyvista/issues/3809)

Here is a static preview, though:

![screenshot (1)](https://user-images.githubusercontent.com/22067021/236373798-f3815a0c-c600-467d-917b-6e3807e162e8.png)

**Comment by banesullivan** [comment]
The "point gaussian" method would be prefered though so I may look at fixing algorithm support for that

**Comment by brendanjmeade** [comment]
This is definitely interesting and great start.  Would the point gaussian be a sort of Gaussian deformation of the surfaces?  The low resolution spheres are not a great look so I'm definitely open to alternatives.  What about this as an idea:  The mesh is a bunch of triangles.  What if instead of spheres we sort extruded the triangles out parallel to their normals to indicate one quantity and color coded them to indicate another.  That would be pretty low polygon count (5 faces per extruded triangle) and might look cool...sort of like an evolving porcupine.  Thoughts?  Interesting discussion.

**Comment by banesullivan** [comment]
> What if instead of spheres we sort extruded the triangles out parallel to their normals to indicate one quantity and color coded them to indicate another.

We can do this! A bit easier, actually... will prototype.

**Comment by banesullivan** [comment]
I'm not sure this is any better or more insightful. 
![screenshot 1](https://user-images.githubusercontent.com/22067021/236865548-3e71e99c-586a-4a96-8c4a-c81ff71bb5a1.png)
![screenshot 2](https://user-images.githubusercontent.com/22067021/236865559-3ed2af1a-85f7-42eb-941e-7b199453e34b.png)

I'm warping the surface by "geometric_moment" and coloring by "cumulative_slip". I think this may be tough to decipher, but perhaps as an animation, this makes sense. 


https://user-images.githubusercontent.com/22067021/236865951-cd932e86-22c9-4bc0-b454-263fa88a0fc7.mov



Let me know if this is different from what you were envisioning

**Comment by brendanjmeade** [comment]
Whoa that's pretty cool!  I think your scheme of warping the surface by "geometric_moment" and coloring by "cumulative_slip". is a good idea because the geometric_moment will increase and decrease but the cumulative_slip only increases.  What you used the banded contour style plotting with this?  that would make it consistent with the style we already have and just add a deforming surface.

**Comment by banesullivan** [comment]
Will do -- this was a first pass. Since this looks good to you, will proceed with making it match the other visualizations

**Comment by banesullivan** [comment]
First pass in 152a20b -- needs some cleanup to get the color bar correct and improve the framerate of the video but here's a look:


https://github.com/brendanjmeade/kale/assets/22067021/fb71fb9f-4872-4aff-a6f7-94d2260c18d7

**Comment by brendanjmeade** [comment]
This is getting there @banesullivan!  Some notes:

- [x] The color bar should be horizontal and centered at the bottom of the figure.
- [x] Time should be centered at the top of the figure.
- [x] The black line representing the mesh boundary stays in initial position.  Can it deform with the mesh?
- [ ] Does the mesh always move upward?  I would have expected it to drop down with each earthquake, especially large ones.  They should be large enough that they, in fact, push the mesh down below its initial value.
- [x] Use just a floor here with white grid lines like I did in the 3 panel version.

No pressure on finishing this for tomorrow.

**Comment by banesullivan** [comment]
Will fix each of these things! 

> Does the mesh always move upward?

Right now, the behavior is to warp in the +Z direction scaled by the variable (`geometric_moment`). Currently, negative values would be needed to go in the -Z direction. I can try to flip this.

**Comment by brendanjmeade** [comment]
If `geometic_moment` is always positive, then it's doing the right thing.  I was pretty sure it went negative in regions that had just experienced a large earthquake.  Can you confirm that `geometric_moment` doesn't go negative here.  I'm either remembering incorrectly or have calculated it in correctly?

**Comment by banesullivan** [comment]
I'll take a look at the values and make sure it's doing what it's supposed to

**Comment by banesullivan** [comment]
As best I can tell, the majority of values for "geometric moment" are positive for the few given time steps I sampled:

![download](https://github.com/brendanjmeade/kale/assets/22067021/a9aeeb90-f9d5-46de-a9fc-0f7102a2a377)

There are negative values, though! And you can see those regions (like on the far right below) move downwards due to the negative values:


https://github.com/brendanjmeade/kale/assets/22067021/44ec94d7-e908-4044-81a4-08e4bda4c3ee
