### ISSUE TITLE
Grid style

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#3]
- Show by default
- Control tick marks
- Set axis labels and fontsize
- Control colorbar position, ticks, and label

**Comment by banesullivan** [comment]
Customizing the grid axes can be a bit of a challenge sometimes. Here are some of the options:
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Renderer.show_bounds.html#show-bounds

I recommend we use the `show_grid()` wrapper of this method. 

I'll set up what I think are some good defaults and let you modify as needed

**Comment by brendanjmeade** [comment]
I've got labels working with: 

```
pl.show_grid(xlabel="longitude", ylabel="latitude", zlabel="depth")
```

I'd like to be able to set the exact tick locations and tick labels.  I've read the documentation but haven't been able to find a way.  Thoughts?

**Comment by banesullivan** [comment]
I'll see what I can do... the grid axes in VTK aren't well supported (there are lots of issues with them). But we may be able to workaround some to get the desired effect. I'll investigate

**Comment by brendanjmeade** [comment]
Thanks for the guidance.  In terms of ticks, I tend to like them very sparse.  Specifically, my goal is just six ticks and labels:

- Minimum depth
- Maximum depth
- Minimum longitude
- Maximum longitude
- Minimum latitude
- Maximum latitude

**Comment by banesullivan** [comment]
So. I took a bit of time to (hackily) fix this in PyVista: https://github.com/pyvista/pyvista/pull/3977

Let's see if that feature branch will merge. We can checkout that branch for now though to get this feature

**Comment by brendanjmeade** [comment]
Looks really go and I can wait to try it after the merge is complete!

**Comment by brendanjmeade** [comment]
@banesullivan Do you have a sense of when the merge might happen?  I'm asking because once we have this and the camera view angle completed, we'll have the polished for all figures and animations.

**Comment by banesullivan** [comment]
I'm not too sure... we ran into some issues that are preventing the merge. I'll try to take a look at the issue again this week with fresh eyes and see if its something I can tackle in an hours work

**Comment by brendanjmeade** [comment]
I see.  How about this as a stopgap measure: Draw a wireframe box around the mesh.  The mins and maxes should just be the mins and maxs of the mesh vertices.  That way we don't rely on creating a proper grid but we get something that provides some orientation information.  It would be 12 lines.  What do you think?

**Comment by brendanjmeade** [comment]
I've been working on this a bit with `pv.Line`.  My primary question is what is the preferred way to get the spatial extent of the mesh limits in Pyvista/VTK.  I've tried looking at `engine.boundary.BOUNDING_BOX` but don't seem to know how to get the quantities that I assume are in it.

**Comment by banesullivan** [comment]
Some examples/alternatives in https://github.com/brendanjmeade/kale/blob/main/grid.ipynb

**Comment by banesullivan** [comment]
Looks like https://github.com/pyvista/pyvista/pull/3977 is about to land

**Comment by brendanjmeade** [comment]
Jaw droppingly awesome!

**Comment by banesullivan** [comment]
Please note the limitations of that recent grid axes work in https://github.com/pyvista/pyvista/issues/4275

**Comment by brendanjmeade** [comment]
@banesullivan With this recent work can you create one example with the now classic 3-panel plot that has labeled axes?
- Axis labels: longitude, latitude, depth
- Ticks only for the minimum and maximum of each axis?

**Comment by banesullivan** [comment]
Will do -- this feature hasn't made it into a release yet so we just have to checkout the latest `main` branch of PyVista until the next release (should be by May 1st)

**Comment by banesullivan** [comment]
Added this via 8e147d4 in the `poster_three_panel.ipynb` noteboook. I added this as a method in `kale.helpers` and recommend using it with a "floor":

```py
pl.add_floor("-z", show_edges=True, edge_color="white", color="lightgray")
helpers.add_bounds(pl)
```
![screenshot](https://user-images.githubusercontent.com/22067021/234022034-4738214b-a18e-4fdc-adaa-aeb239bce65b.png)

**Comment by banesullivan** [comment]
https://github.com/brendanjmeade/kale/commit/8e147d4ba4feed3d530bd2bb6ead35808b943636#commitcomment-110548841

> control font sizes/styles/weights

**Comment by brendanjmeade** [comment]
Adding these axis labels to the canonical notebook that produces a single figure would be great.  Role that into: https://github.com/brendanjmeade/kale/issues/17
