### ISSUE TITLE
Different colormaps for each of the subplots in the 4-panel figure

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#4]

**Comment by banesullivan** [comment]
Can you list which colormap you'd like to use for each variable?

**Comment by banesullivan** [comment]
Updated the notebook to specify a colormap for each variable

**Comment by banesullivan** [comment]
Here is a preview:

![screenshot](https://user-images.githubusercontent.com/22067021/216457912-496b8162-97c4-4cdd-a7b6-9159363a0557.png)

**Comment by brendanjmeade** [comment]
Looks good!
