### ISSUE TITLE
Control over perspective view

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#5]
<img width="615" alt="perspective_cartoon" src="https://user-images.githubusercontent.com/4225359/216212090-95353d64-a507-439b-829a-43aa9dab85e7.png">

**Comment by brendanjmeade** [comment]
@banesullivan See pyvista slack conversation at: https://pyvista.slack.com/archives/CBA5095UH/p1679071770504499?thread_ts=1679026658.845809&cid=CBA5095UH

**Comment by banesullivan** [comment]
the `view_angle` on the camera is indeed what we want to adjust: https://docs.pyvista.org/api/core/_autosummary/pyvista.Camera.view_angle.html#view-angle

Problem is that there is a discrepancy between the Trame's vtk view (what we use in the notebooks) and the interaction events in VTK directly. Trame is using the view angle to perform zoom's which is not what we need. This may need to get fixed upstream before you can fully leverage this.

```py
import pyvista as pv

box = pv.Cube()

pl = pv.Plotter(notebook=0)
pl.add_mesh(box)
pl.enable_trackball_style()

def set_view_angle(angle):
    pl.camera.view_angle = angle
    
pl.add_slider_widget(set_view_angle, [0, 180], value=30)

pl.show()
```

![Screen Shot 2023-03-21 at 12 26 17 PM](https://user-images.githubusercontent.com/22067021/226706254-e142bf26-c373-4e5e-bbd4-7da1678d9169.png)

**Comment by brendanjmeade** [comment]
@banesullivan Thanks for the update. I never would have figured this out.  Understood and let's focus our attention on other things.

**Comment by banesullivan** [comment]
This will be fixed by https://github.com/Kitware/trame-vtk/pull/31 in the next version of `trame-vtk` which should be out in a few days

**Comment by psavery** [comment]
It's merged! This issue should be fixed if you update your `trame-vtk` to version 2.4.0.
