### ISSUE TITLE
Plotly plots with four panel plots

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#6]
- Located below the 4 panel
- Use as time slider
- Stem plot for event magnitudes
- Line/fill plot for event probabilities

**Comment by banesullivan** [comment]
@brendanjmeade, would you please share the original code you had to make the plots you had for this?

**Comment by brendanjmeade** [comment]
@banesullivan See: https://github.com/brendanjmeade/skies/blob/aeabf12f5d8e771a39ace97d2fa010b575ddf7e6/skies/skies.py#L1620

**Comment by brendanjmeade** [comment]
Closing with new design target: https://github.com/brendanjmeade/kale/issues/12
