### ISSUE TITLE
Create and save and animation through time for a single quantity

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#7]

**Comment by banesullivan** [comment]
I added some example code(which we can work to improve) that demonstrates how to write a movie. This is actually pretty easy and the key is getting the visualization looking the way you want first.

Here's a rough preview:

https://user-images.githubusercontent.com/22067021/216497550-c6b16521-4396-4d31-bb18-b739da0acd6c.mp4

**Comment by banesullivan** [comment]
See 07da99a

**Comment by brendanjmeade** [comment]
Wow, this is getting so good.  When trying to get this to run I get an error that looks `imageio` related.
<img width="1279" alt="Screenshot 2023-02-05 at 10 22 49 PM" src="https://user-images.githubusercontent.com/4225359/216877384-9d98919b-359d-4da0-a3f1-70f29a2b2864.png">

**Comment by banesullivan** [comment]
I think a `conda install imageio` should do the trick... I'll update the conda env file

**Comment by brendanjmeade** [comment]
`imageio` is installed now but the error is still there.  Not sure?

**Comment by banesullivan** [comment]
Ah I think we need both `imageio>=2.5.0` and `imageio-ffmpeg`

**Comment by brendanjmeade** [comment]
Ok I've reinstalled the kale environment from the updated environment.yml and am now getting the following error related to the banded contour plot in the movie generation loop: 
<img width="813" alt="Screenshot 2023-02-08 at 1 06 43 PM" src="https://user-images.githubusercontent.com/4225359/217615746-74cb8977-5ae3-47c7-855e-93e3bc12f405.png">

**Comment by banesullivan** [comment]
Woops, that was a late-night mistake. Will fix right now

**Comment by banesullivan** [comment]
Fixed in 3ace6cc

**Comment by brendanjmeade** [comment]
This is working correct now and renders movies quite quickly!  Thanks @banesullivan!
