### ISSUE TITLE
Control size and location of colorbar

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#8]
- Vertical colorbar
- Set ticks
- Font size

**Comment by banesullivan** [comment]
The scalar bar is customizable as outlined in this example: https://docs.pyvista.org/examples/02-plot/scalar-bars.html

Perhaps we can get started on a minimal example here and then incorporate the same `**kwargs` into the module

```py
import pyvista as pv
from pyvista import examples

# Load St Helens DEM and warp the topography
mesh = examples.download_st_helens().warp_by_scalar()

sargs = dict(
    # Position (coordinates are on the viewport)
    vertical=True,
    height=0.25,  
    position_x=0.05, 
    position_y=0.05,
    # Labels
    title_font_size=20,
    label_font_size=16,
    n_labels=3,
    italic=True,
    fmt="%.1f",
    font_family="arial",
    shadow=True,
)

p = pv.Plotter()
p.add_mesh(mesh, scalar_bar_args=sargs)
p.show()
```
![screenshot](https://user-images.githubusercontent.com/22067021/216373744-64b64d74-37e1-4906-a429-824229e836f2.png)

**Comment by banesullivan** [comment]
The options are documented here: https://docs.pyvista.org/api/plotting/_autosummary/pyvista.BasePlotter.add_scalar_bar.html#add-scalar-bar

**Comment by banesullivan** [comment]
Updated the display parameters in 3d8b977. We can modify these to get your desired effect
