### ISSUE TITLE
Bane's ideas for adding some geographic context

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#9]
This is lower priority for me and I'm open-minded here.  Are you thinking of a coastline, something else?

**Comment by banesullivan** [comment]
This could end up getting a bit involved as we need to find some geospatial data in the same region then deal with coordinate systems. I'll toy with this if I have a second but won't spend too much time looking into it

**Comment by brendanjmeade** [comment]
I say skip it.  It's not a high priority item for me.
